apiVersion: v2
appVersion: 1.118.0
name: opencost-lens
description: OpenCost and OpenCost UI - Lens customized version
type: application
keywords:
- cloud-costs
- cost-optimization
- finops
- monitoring
- opencost
- lens
version: 1.0.0
maintainers:
  - name: gablyu-oci
annotations:
  upstream: https://github.com/opencost/opencost-helm-chart
  upstreamVersion: "2.4.0"
sources:
  - https://github.com/gablyu-oci/opencost-helm-chart
home: https://github.com/gablyu-oci/opencost-helm-chart
