opencost:
  prometheus:
    internal:
      namespaceName: lens
      serviceName: lens-prometheus-server
      port: 9090

  dataRetention:
    dailyResolutionDays: 30

  exporter:
    defaultClusterId: "default-cluster"
    replicas: 1
    image:
      registry: iad.ocir.io
      repository: iduyx1qnmway/lens-metric-collector/opencost
      tag: latest
      pullPolicy: Always
    resources:
      requests:
        cpu: "10m"
        memory: "55Mi"
      limits:
        memory: "1Gi"
    persistence:
      enabled: true
      storageClass: "oci-bv"
      accessMode: ReadWriteOnce
      size: 50Gi
    env:
      - name: USE_CUSTOM_PROVIDER
        value: "true"

  customPricing:
    enabled: true
    createConfigmap: true
    configmapName: pricing-configs
    configPath: /tmp/custom-config
    provider: default
    costModel:
      CPU: 0.031611
      spotCPU: 0.006655
      RAM: 0.004237
      spotRAM: 0.000892
      GPU: 6
      storage: 0.00005479452
      zoneNetworkEgress: 0.01
      regionNetworkEgress: 0.01
      internetNetworkEgress: 0.143

  carbonCost:
    enabled: false

  cloudCost:
    enabled: false
